#!/bin/bash

# Variables:
compiler=g++
output=main.o

# Clean up the current repo:
rm -f ./$output

# Functions:
usage () {
    echo "compile"
    echo "  [-c <compiler>] Specify a different compiler than g++."
}

# Compile:
$compiler -std=c++11 -g main.cpp functions/functions.cpp functions/bigint.cpp -o $output

# Running:
./$output data/training_languages/* data/testing_languages/*

#