#!/bin/bash

#clear

# Variables:
compiler=g++
output=main.o
FLAGS="-pedantic -Wall -Wextra -Wdisabled-optimization -Wmissing-include-dirs
 -Wnoexcept -Wredundant-decls -Wswitch-default -Wundef -Werror -Wno-unused"

# Halt on first error
set -e

# Clean up the current repo:
rm -f ./$output

# Functions:
usage () {
    echo "compile"
    echo "  [-c <compiler>] Specify a different compiler than g++."
}

# Compile:
$compiler $FLAGS -std=c++11 -Ofast -g main.cpp functions/functions.cpp functions/bigint.cpp -o $output

# Running:
time ./$output data/training_languages/* data/testing_languages/english

#